import type { AvailabilityOverride } from 'types/dates'
import { scheduleDates } from './lib/dates/scheduleDates'
import { fetchMatchSettings } from './lib/fetchSettings'
import { fetchMatchSubmissions } from './lib/fetchSubmissions'
import { createDatesTable } from './lib/dates/createDatesTable'
import { createSlotsTables } from './lib/dates/createSlotsTable'
import { useEnv } from './utils/env'
import { safeAsync } from './utils/safeAsync'
import { createLogger } from './utils/logger'
import {
	getRoundSettingsForSpeeddates,
	resolveMatchingSchemaFile,
	createScopedFileName,
} from './utils/helpers'
import { buildDateDataset } from './lib/dates/buildDateDataset'
import readXlsxFile from 'read-excel-file/node'

const { ROUND, INPUT_DIR, OUTPUT_DIR } = useEnv()
const logger = createLogger()

/**
 * Create availability overrides for specific entities.
 *
 * These overrides enforce constraints on the scheduling algorithm, such as:
 * - forcing availability for specific trainees
 * - restricting availability for specific schools
 *
 * Important:
 * - Slot numbers are 1-based
 * - Overrides take precedence over default "fully available" behavior
 *
 * @param numberOfSlots - Total number of available slots in the current round
 * @returns List of availability overrides
 *
 * @example
 * ```ts
 * createDateOverrides(10)
 * // => [
 * //   {
 * //     name: 'Henk Herrie',
 * //     type: 'trainee',
 * //     availability: [1, 2, 3, 4, 5, 6, 7],
 * //   },
 * //   {
 * //     name: 'Luilekkerland Lyceum',
 * //     type: 'school',
 * //     availability: [6, 7, 8, 9, 10],
 * //   },
 * // ]
 * ```
 */
export function createDateOverrides(_numberOfSlots: number): AvailabilityOverride[] {
	return []
}

/**
 * Speed date scheduling script entrypoint.
 *
 * High-level flow:
 * 1. Fetch matching settings (slot configuration per round)
 * 2. Fetch submissions (trainee + school data)
 * 3. Read matching schema Excel (input from previous step)
 * 4. Build normalized dataset (domain model)
 * 5. Run scheduling algorithm (assign trainees → slots)
 * 6. Generate Excel outputs:
 *    - dates schema (ordered matches per school)
 *    - slot schedules (by school + by trainee)
 *
 * This file should remain orchestration-only:
 * - no business logic
 * - no data transformation logic
 * - no scheduling logic
 */
async function main(): Promise<void> {
	/**
	 * Guard: speed dates are only supported for day_1 and day_2
	 */
	if (ROUND === 'final_3') {
		throw new Error('The speed date script only supports day_1 and day_2 rounds')
	}

	/**
	 * STEP 1: Fetch matching settings
	 *
	 * Contains:
	 * - slot count
	 * - slot duration
	 * - round-specific configuration
	 */
	const { data: settings, error: settingsError } = await safeAsync(fetchMatchSettings)

	if (settingsError || !settings) {
		logger.warn('An error occurred while fetching match settings')
		logger.error(settingsError)
		process.exit(1) // hard fail → nothing else can run without this
		return
	}

	/**
	 * Resolve settings specific to the current round (day_1, day_2)
	 */
	const roundSettings = getRoundSettingsForSpeeddates(settings, ROUND)

	logger.info(`Running speed date algorithm for ${ROUND}`)

	/**
	 * STEP 2: Fetch submissions
	 *
	 * Contains:
	 * - trainees
	 * - schools
	 * - preferences (used indirectly via matching schema)
	 */
	const { data: submissions, error: submissionsError } = await safeAsync(() =>
		fetchMatchSubmissions({
			matchingId: settings.currentMatching.id,
			round: ROUND,
		}),
	)

	if (submissionsError || !submissions) {
		logger.warn('An error occurred while fetching match submissions')
		logger.error(submissionsError)
		process.exit(1) // cannot proceed without input data
		return
	}

	/**
	 * STEP 3: Read matching schema Excel
	 *
	 * This file is generated by the matching script and contains:
	 * - schools as rows
	 * - trainees as columns
	 * - match indicators in cells
	 */
	const rows = await readXlsxFile(resolveMatchingSchemaFile(ROUND, { inputDir: INPUT_DIR }))

	/**
	 * STEP 4: Build availability overrides
	 *
	 * These influence scheduling constraints.
	 */
	const overrides = createDateOverrides(roundSettings.slots)
	const overrideNames = overrides.map((o) => o.name)

	/**
	 * STEP 5: Build dataset (pure transformation)
	 *
	 * Transforms:
	 * - Excel rows
	 * - submissions
	 *
	 * Into:
	 * - structured match data
	 * - normalized entities
	 */
	const dataset = buildDateDataset({
		rows,
		submissions,
		overrideNames,
	})

	logger.info('Dataset built:', {
		schools: dataset.schools.length,
		trainees: dataset.trainees.length,
		matches: dataset.matches.length,
	})

	/**
	 * STEP 6: Run scheduling algorithm
	 *
	 * Assigns trainees to slots per school while respecting:
	 * - availability constraints
	 * - no double booking
	 * - greedy first-fit strategy
	 */
	const schedule = scheduleDates({
		dataset,
		overrides,
		numberOfSlots: roundSettings.slots,
	})

	logger.info('Scheduling complete', {
		unassigned: schedule.unassignedMatches.length,
	})

	/**
	 * STEP 7: Generate Excel outputs
	 *
	 * - dates schema → ordered matches per school
	 * - slot schedules → by school + by trainee
	 */
	await createDatesTable({
		matches: dataset.matches,
		numberOfSlots: roundSettings.slots,
		outputPath: `${OUTPUT_DIR}/${createScopedFileName('dates_schema', ROUND)}`,
	})

	await createSlotsTables({
		schedule,
		numberOfSlots: roundSettings.slots,
		outputDir: OUTPUT_DIR,
		round: ROUND,
	})
}

await main()
